// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr6Po3h23AObTCfF2FaNvM7c9ZsAg7OWI',
    appId: '1:462936385343:web:997f2817c6ed054dab158a',
    messagingSenderId: '462936385343',
    projectId: 'chatbox-36803',
    authDomain: 'chatbox-36803.firebaseapp.com',
    storageBucket: 'chatbox-36803.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ1jcm5olEBYrghmo6uPEEtkJdcvowZYc',
    appId: '1:462936385343:android:3798d13c3f46ba1cab158a',
    messagingSenderId: '462936385343',
    projectId: 'chatbox-36803',
    storageBucket: 'chatbox-36803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6-vCBwHw3nixuYVqJ6xdRU3miLGCYwfI',
    appId: '1:462936385343:ios:4d371b62f6675e21ab158a',
    messagingSenderId: '462936385343',
    projectId: 'chatbox-36803',
    storageBucket: 'chatbox-36803.appspot.com',
    iosClientId: '462936385343-cfs0dpeivfkcgeo317r13biv8c9lfu9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6-vCBwHw3nixuYVqJ6xdRU3miLGCYwfI',
    appId: '1:462936385343:ios:4d371b62f6675e21ab158a',
    messagingSenderId: '462936385343',
    projectId: 'chatbox-36803',
    storageBucket: 'chatbox-36803.appspot.com',
    iosClientId: '462936385343-cfs0dpeivfkcgeo317r13biv8c9lfu9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbox',
  );
}
