// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVpcX62IqlCzTErjnalceapkYaBP2zOHk',
    appId: '1:645937539614:web:ddfe99fd31a266ac96dc0f',
    messagingSenderId: '645937539614',
    projectId: 'zoom-clone-99d0c',
    authDomain: 'zoom-clone-99d0c.firebaseapp.com',
    storageBucket: 'zoom-clone-99d0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxJFfqQla3B4WLzQLp5epaHITovwd3Ss4',
    appId: '1:645937539614:android:4d731ad6ea0c443f96dc0f',
    messagingSenderId: '645937539614',
    projectId: 'zoom-clone-99d0c',
    storageBucket: 'zoom-clone-99d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD72HLMfV2DrYZe_tsFOk-JlUJlGba1N2k',
    appId: '1:645937539614:ios:dcc5629645e7b4c396dc0f',
    messagingSenderId: '645937539614',
    projectId: 'zoom-clone-99d0c',
    storageBucket: 'zoom-clone-99d0c.appspot.com',
    iosClientId: '645937539614-s54vfqs9ci0vpiqi2159s762pa1idhjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD72HLMfV2DrYZe_tsFOk-JlUJlGba1N2k',
    appId: '1:645937539614:ios:dcc5629645e7b4c396dc0f',
    messagingSenderId: '645937539614',
    projectId: 'zoom-clone-99d0c',
    storageBucket: 'zoom-clone-99d0c.appspot.com',
    iosClientId: '645937539614-s54vfqs9ci0vpiqi2159s762pa1idhjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
